[package]
name = "raytrace"
version = "0.1.0"
authors = ["Sam Shippey <sshippey@pdx.edu>", "Katelyn Rule <krule@pdx.edu>"]
edition = "2018"

[dependencies]
nalgebra = "0.18"
image = "0.21.2"
ncollide3d = "0.19.2"
rayon = "1.1"
